### PR TITLE
Add bob exercise

### PR DESCRIPTION
**Pull request by kenden**
I used the python version as a base for this.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Would you mind rebasing this onto master and resolve the conflict? (I'm guessing it's the config.json file)

**Comment by kenden** [comment]
@kytrinyx I rebased on master, 
there were more than one PR modifying config.json indeed!

**Comment by kenden** [comment]
Note to self. Match the test with list of test from:
https://github.com/exercism/x-common/blob/master/bob.json

**Comment by kytrinyx** [comment]
Sweet, thanks @kenden. Do you want to add the missing tests before I take one last look at this for merging?

**Comment by kenden** [comment]
Yes, I'll add a few test cases, thanks for checking!

**Comment by kenden** [comment]
Test added, but now the example still needs fixing

**Comment by kytrinyx** [comment]
Classic :)

**Comment by kenden** [comment]
One test still needs to pass, still working on it.

**Comment by kenden** [comment]
It should be good to go now.

**Comment by kytrinyx** [comment]
Thanks, @kenden!

**Pull request merged**
