### PR TITLE
Fix hamming test containing invalid DNA letters

### PR DESCRIPTION
**Pull request by kenden**
Also added a couple of tests to avoid this.

### CODE REVIEW

**Comment by adelcambre** [comment]
Can you add the code that makes this pass to the example? Thanks!

**Comment by kenden** [comment]
@adelcambre I added code to make the example.sh pass the extra tests

**Comment by kenden** [comment]
@adelcambre I am having second thoughts about adding new tests and new code to the example:
This make the exercise quite a bit more complicated. The examples in Go or Python do not have this checks.
I think I will simply replace this:
 @test "Long identical strands have hamming distance of zero" {
 -  run bash hamming.sh CATSCATS CATSCATS
 +  run bash hamming.sh CATGCATG CATGCATG
to not have some invalid DNA in there (just because it doesn't look good, nothing else).
And that's it.
What do you think?

**Comment by kytrinyx** [comment]
@kenden I think that making the replacement you suggest sounds good.

**Comment by kenden** [comment]
@kytrinyx I replaced the extra tests and extra code by just a little cleanup.

**Comment by kytrinyx** [comment]
Thanks!

**Pull request merged**
