### PR TITLE
Add raindrops exercise

### PR DESCRIPTION
**Pull request by kenden**
Based on Ruby, Php, Rust versions

### CODE REVIEW

**Comment by kytrinyx** [comment]
Nice, thank you!

**Comment by kytrinyx** [comment]
I don't know if this is documented anywhere yet, but some exercises also have a JSON file with canonical data, which can sometimes make it easier to implement.

If you go to this URL http://x.exercism.io/v3/tracks/bash/todo (you'll want a json plugin for the browser), then look for the "data" key. If it's null you're out of luck, but if it has a URL, that should link to a file with test inputs/outputs that we've extracted from existing implementations.

**Comment by kenden** [comment]
@kytrinyx thanks!
I'll take a look. I think a few bash exercises already needs fixing from this file :)

**Comment by kytrinyx** [comment]
Haha, that's what I get for being so behind on documenting things.

Thank you :)

**Pull request merged**
