### PR TITLE
Add track icon

### PR DESCRIPTION
**Pull request by joeltaylor**
Add track icon in reference to https://github.com/exercism/xbash/issues/18

### CODE REVIEW

**Comment by kotp** [comment]
@exercism/track-maintainers bump... @kytrinyx Anyone in here?

**Comment by verdammelt** [comment]
Looks good to me. 

@joeltaylor where did that icon come from? Does Bash have an 'official' logo?

**Comment by kotp** [comment]
Same line of questions I had on Ruby ;)  I haven't looked deeply where the graphics came from nor where attribution should go.  But I think it is important.

**Comment by markijbema** [comment]
It seems to be the official logo:
https://github.com/MaxCDN/shml/wiki/Official-Bash-Sticker-Giveaway

**Comment by markijbema** [comment]
I cannot find anything on the license of the logo though

**Comment by joeltaylor** [comment]
@verdammelt I pulled the icon from https://github.com/exercism/exercism.io/blob/master/public/img/tracks/bash.png and assumed it was the proper one.

**Comment by kytrinyx** [comment]
The Ruby logo came from the Vienna.rb group with permission.

See https://github.com/exercism/exercism.io/blob/master/ATTRIBUTION.md for all the attributions for each logo.

**Comment by kytrinyx** [comment]
Thank you!

**Comment by kotp** [comment]
Thanks @kytrinyx not difficult to find, just hadn't searched even topically.  :blush:

**Pull request merged**
